### ISSUE TITLE
Memory error in GUI

### ISSUE THREAD

**Issue by delmic** [delmic/odemis#22]
This happened once so far.
Seems to start with problem in cropping the image, then error in writing it in TIFF, and from then on MemoryErrors (maybe due to memory corruption by libtiff?).

```
2014-11-17 10:31:06,160 INFO    text:696: Received the new value '1.0' to set while in focus
2014-11-17 10:33:52,680 INFO    acquisition:213: Snapshot saved as file '/home/secom/Pictures/141117/InsQD655_Hoechst_1s_100mW.ome.tiff'.
2014-11-17 10:37:31,716 INFO    text:696: Received the new value '1280.0' to set while in focus
2014-11-17 10:43:16,943 ERROR   main:273: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/canvas.py", line 1344, in on_left_up
    self.update_drawing()
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/miccanvas.py", line 394, in update_drawing
    super(DblMicroscopeCanvas, self).update_drawing()
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/canvas.py", line 1535, in update_drawing
    self.draw()
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/miccanvas.py", line 758, in draw
    super(DblMicroscopeCanvas, self).draw()
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/canvas.py", line 823, in draw
    self._draw_merged_images(self.ctx)
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/canvas.py", line 876, in _draw_merged_images
    blend_mode=im.metadata['blend_mode']
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/canvas.py", line 976, in _draw_image
    im_data, tl = self._get_sub_img(intersection, b_im_rect, im_data, total_scale)
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/canvas.py", line 1139, in _get_sub_img
    sub_im_x:sub_im_x + sub_im_w].copy()
type

2014-11-17 10:43:16,959 DEBUG   canvas:478: Buffer size changed, redrawing...
2014-11-17 10:43:16,959 DEBUG   canvas:514: Resizing buffer size to (2291, 1922)
2014-11-17 10:43:16,960 ERROR   main:273: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/miccanvas.py", line 530, in on_size
    super(DblMicroscopeCanvas, self).on_size(event)
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/canvas.py", line 480, in on_size
    self.update_drawing()
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/miccanvas.py", line 394, in update_drawing
    super(DblMicroscopeCanvas, self).update_drawing()
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/canvas.py", line 1535, in update_drawing
    self.draw()
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/miccanvas.py", line 758, in draw
    super(DblMicroscopeCanvas, self).draw()
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/canvas.py", line 823, in draw
    self._draw_merged_images(self.ctx)
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/canvas.py", line 876, in _draw_merged_images
    blend_mode=im.metadata['blend_mode']
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/canvas.py", line 976, in _draw_image
    im_data, tl = self._get_sub_img(intersection, b_im_rect, im_data, total_scale)
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/canvas.py", line 1139, in _get_sub_img
    sub_im_x:sub_im_x + sub_im_w].copy()
type

2014-11-17 10:43:20,347 ERROR   main:273: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/miccanvas.py", line 530, in on_size
    super(DblMicroscopeCanvas, self).on_size(event)
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/canvas.py", line 480, in on_size
    self.update_drawing()
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/miccanvas.py", line 394, in update_drawing
    super(DblMicroscopeCanvas, self).update_drawing()
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/canvas.py", line 1535, in update_drawing
    self.draw()
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/miccanvas.py", line 758, in draw
    super(DblMicroscopeCanvas, self).draw()
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/canvas.py", line 823, in draw
    self._draw_merged_images(self.ctx)
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/canvas.py", line 876, in _draw_merged_images
    blend_mode=im.metadata['blend_mode']
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/canvas.py", line 976, in _draw_image
    im_data, tl = self._get_sub_img(intersection, b_im_rect, im_data, total_scale)
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/canvas.py", line 1139, in _get_sub_img
    sub_im_x:sub_im_x + sub_im_w].copy()
type

2014-11-17 10:43:20,491 DEBUG   canvas:478: Buffer size changed, redrawing...
2014-11-17 10:43:20,491 DEBUG   canvas:514: Resizing buffer size to (2291, 1922)
2014-11-17 10:43:20,492 ERROR   main:273: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/miccanvas.py", line 530, in on_size
    super(DblMicroscopeCanvas, self).on_size(event)
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/canvas.py", line 480, in on_size
    self.update_drawing()
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/miccanvas.py", line 394, in update_drawing
    super(DblMicroscopeCanvas, self).update_drawing()
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/canvas.py", line 1535, in update_drawing
    self.draw()
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/miccanvas.py", line 758, in draw
    super(DblMicroscopeCanvas, self).draw()
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/canvas.py", line 823, in draw
    self._draw_merged_images(self.ctx)
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/canvas.py", line 876, in _draw_merged_images
    blend_mode=im.metadata['blend_mode']
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/canvas.py", line 976, in _draw_image
    im_data, tl = self._get_sub_img(intersection, b_im_rect, im_data, total_scale)
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/canvas.py", line 1139, in _get_sub_img
    sub_im_x:sub_im_x + sub_im_w].copy()
type

2014-11-17 10:43:21,736 DEBUG   canvas:1323: Drag started at (315, 1012)
2014-11-17 10:43:21,829 ERROR   main:273: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/canvas.py", line 1344, in on_left_up
    self.update_drawing()
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/miccanvas.py", line 394, in update_drawing
    super(DblMicroscopeCanvas, self).update_drawing()
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/canvas.py", line 1535, in update_drawing
    self.draw()
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/miccanvas.py", line 758, in draw
    super(DblMicroscopeCanvas, self).draw()
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/canvas.py", line 823, in draw
    self._draw_merged_images(self.ctx)
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/canvas.py", line 876, in _draw_merged_images
    blend_mode=im.metadata['blend_mode']
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/canvas.py", line 976, in _draw_image
    im_data, tl = self._get_sub_img(intersection, b_im_rect, im_data, total_scale)
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/canvas.py", line 1139, in _get_sub_img
    sub_im_x:sub_im_x + sub_im_w].copy()
type

2014-11-17 10:43:22,200 DEBUG   canvas:1323: Drag started at (166, 1120)
2014-11-17 10:43:22,321 DEBUG   canvas:316: Dynamic cursor reset
2014-11-17 10:43:23,511 DEBUG   buttons:795: ViewButton already active
2014-11-17 10:44:34,588 ERROR   log:37: Failed to save snapshot
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odemis/gui/cont/acquisition.py", line 211, in snapshot_viewport
    exporter.export(filepath, raw_images, thumbnail)
  File "/usr/lib/python2.7/dist-packages/odemis/dataio/tiff.py", line 1427, in export
    _saveAsMultiTiffLT(filename, data, thumbnail)
  File "/usr/lib/python2.7/dist-packages/odemis/dataio/tiff.py", line 1320, in _saveAsMultiTiffLT
    f.write_image(data[i], write_rgb=write_rgb, compression=c)
  File "/usr/lib/python2.7/dist-packages/libtiff/libtiff_ctypes.py", line 555, in write_image
    WriteStrip(0, arr.ctypes.data, size)
  File "/usr/lib/python2.7/dist-packages/libtiff/libtiff_ctypes.py", line 782, in WriteEncodedStrip
    assert r.value==size,`r.value, size`
AssertionError: (-1, 8388608)
2014-11-17 10:44:34,615 DEBUG   canvas:478: Buffer size changed, redrawing...
2014-11-17 10:44:34,615 DEBUG   canvas:514: Resizing buffer size to (2295, 1958)
2014-11-17 10:44:34,616 DEBUG   viewport:466: Canvas HFW too small! Setting it to 0.01
2014-11-17 10:44:34,637 DEBUG   canvas:478: Buffer size changed, redrawing...
2014-11-17 10:44:34,638 DEBUG   canvas:514: Resizing buffer size to (2291, 1922)
2014-11-17 10:45:20,084 ERROR   log:37: Subscriber <odemis.model._core.WeakMethodBound object at 0xc19da0c> raised exception when receiving value 1416217520.05
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odemis/model/_vattributes.py", line 96, in notify
    l(v)
  File "/usr/lib/python2.7/dist-packages/odemis/model/_core.py", line 382, in __call__
    return self.f(ins, *arg, **kwargs)
  File "<string>", line 2, in _onViewImageUpdate
  File "/usr/lib/python2.7/dist-packages/odemis/gui/util/__init__.py", line 118, in ignore_dead
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/miccanvas.py", line 382, in _onViewImageUpdate
    self._convert_streams_to_images()
  File "/usr/lib/python2.7/dist-packages/odemis/gui/comp/miccanvas.py", line 352, in _convert_streams_to_images
    rgba_im = img.format_rgba_darray(rgbim)
  File "/usr/lib/python2.7/dist-packages/odemis/gui/util/img.py", line 45, in format_rgba_darray
    rgba = numpy.empty(rgba_shape, dtype=numpy.uint8)
MemoryError
```

**Comment by delmic** [comment]
There might be several memory leaks, but one obvious is that when opening a new set of data in the analysis tab, the previous data (streams) are not garbage collected.

Starting point is to check StreamBarController.clear() removes all references to the streams and stream panels. Could be partly related to Stream._image_thread() keeping a ref to self. It could also be related to stream panel not being derefed.
