### ISSUE TITLE
TMCM driver reports IOError sometimes during a move

### ISSUE THREAD

**Issue by delmic** [delmic/odemis#31]
```
2015-03-27 14:13:55,624 INFO    __init__:763: Failed to apply focus move
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odemis/gui/model/__init__.py", line 761, in _moveFocus
    f.result()
  File "/usr/lib/python2.7/dist-packages/Pyro4/futures.py", line 300, in result
    return self.__get_result()
  File "/usr/lib/python2.7/dist-packages/Pyro4/futures.py", line 284, in __get_result
    raise self._exception
IOError: Received only 0 bytes after 1, 6, 8, 2, 0 (17)
```
That seems corresponding to TMCM._isOnTarget().

Or:
```
2015-03-27 14:14:15,724 INFO    __init__:763: Failed to apply focus move
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odemis/gui/model/__init__.py", line 761, in _moveFocus
    f.result()
  File "/usr/lib/python2.7/dist-packages/Pyro4/futures.py", line 300, in result
    return self.__get_result()
  File "/usr/lib/python2.7/dist-packages/Pyro4/futures.py", line 284, in __get_result
    raise self._exception
IOError: Received only 0 bytes after 1, 4, 1, 2, 8642 (235)
```
That's a relative move request.

Apparently, afterwards, the controller keeps working fine.
=> Need to try harder contacting the controller?

**Comment by delmic** [comment]
That was caused by a second instance of the TMCM driver running in parallel (and keep asking for the temperature). So the commands received wrong message back, skipped it, and never got the expected message, read by the other driver.
